### ISSUE TITLE
Closing upon death.

### ISSUE THREAD

**Issue by 0xasmit** [CarlKuhligk/ShellShockLiveRuler#1]

**Comment by 0xasmit** [comment]
The program closes each time you die. Very nice overall outside of that though. I was curious when things like vortex/bumper/bounces would be supported though?

**Comment by theautomatist** [comment]
i tested it, so the way how it works is the following:

1. start shellshock live
2. go in fireing mode or an other gamemode (this will generate a function in memory wich the programm is looking for)
3. run the digital ruler as admin
4. look in the console, if it finds the right memory location, is will display it (Hockaddress: ......)
5. if you shoot, the programm will get the addresses of all players and can calulate and display the projectile

hope this is usefull, thx for feedback

**Comment by 0xasmit** [comment]
Ohh thank you that's very neat. I took a peek and saw you had code laid out for blackholes/bounces/rebounds is that something you planned on implementing sometime soon in the future?

**Comment by theautomatist** [comment]
take a look in the wiki section.
i have not much experience with github, im still learning.
if i have a lot of time, i will do it. maybe someone else can do it :D .

the most difficult (time consuming) task is to find the memory addresses of blackholes and co.

**Comment by 0xasmit** [comment]
very much appreciated. i'm not too experienced with unity games so it's rather confusing for me but after poking around in your code I might be able to figure it out and get some form of grip on what's happening to help out. 

nonetheless i appreciate the work you've put into this project already <3

**Comment by theautomatist** [comment]
if you need some help i can explain it to you.
Discord #5360

**Comment by 0xasmit** [comment]
ohh that'd be nice i've sent you a friend request

**Comment by theautomatist** [comment]
Carl Kuhligk#5360

**Comment by furyzenblade** [comment]
@CarlKuhligk 
> Carl Kuhligk#5360

Mind accepting me on discord too? (Fury Zenblade#1337)
I'd like to add some features to the ruler
