### ISSUE TITLE
Just An Information

### ISSUE THREAD

**Issue by gameplayoffert** [CarlKuhligk/ShellShockLiveRuler#3]
Hi, i saw your software, i compile it in x86 and to be honnest your software is just awesome i don't have the words for that (sorry i'm not english). I have 1000 questions and probably more about this software so do you have discord ? i ask that because you seems to know a lot of things about cheat engine and i'm very interested about this thing so where can i contact you ?

**Comment by theautomatist** [comment]
hi, sure, add me :) 

Carl Kuhligk#5360
